version: '3.9'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:16-alpine
    container_name: metropolitan_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: metropolitan_dev
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: metropolitan_dev_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=tr_TR.utf8"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - metropolitan_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metropolitan_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache for Development
  redis-dev:
    image: redis:7-alpine
    container_name: metropolitan_redis_dev
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - metropolitan_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for Database Management (Development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: metropolitan_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@metropolitan.local
      PGADMIN_DEFAULT_PASSWORD: admin_password_123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - metropolitan_dev_network
    depends_on:
      - postgres-dev
    profiles:
      - tools

  # Redis Commander for Redis Management (Development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: metropolitan_redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis-dev:6379
    ports:
      - "8081:8081"
    networks:
      - metropolitan_dev_network
    depends_on:
      - redis-dev
    profiles:
      - tools

# Networks
networks:
  metropolitan_dev_network:
    driver: bridge

# Volumes
volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_data:
    driver: local